description: 'This Yeager Workflow component is responsible for collecting data related
  to Nike employees in the IT department from multiple trusted data sources and/or
  public platforms, and sending the extracted data to Salesforce. It processes the
  data and ensures the integrity of the data before transferring it to the Salesforce
  platform.

  '
input-class: NikeITPersonasCollectionAndSalesforceIn
name: NikeITPersonasCollectionAndSalesforce
output-class: NikeITPersonasCollectionAndSalesforceOut
parameters: {}
